### ISSUE TITLE
LPS announcer: "You have lost the lead" while waiting for next round

### ISSUE THREAD

**Issue by cinnamon189** [PadWorld-Entertainment/worldofpadman#325] opened 2024-11-09 21:35 UTC
I just joined an LPS match among bots that had already started (so it said "Waiting for next round!" for me). After one of the bots got fragged, the announcer said "You have lost the lead".

**Comment by kai-li-wop** [comment] 2024-11-14 17:23
I could not reproduce this problem. Please try to recreate it and provide instructions on how to recreate it. I have actually found other problems when joining a running LPS match later, but not this one.

**Comment by cinnamon189** [comment] 2024-11-16 23:02
That's strange, I cannot reproduce it either. I even tried to manually have my camera follow a bot, suspecting that I heard an announcement for one of the bots. Maybe the bug only appears under special circumstances. In any case, it is nothing obtrusive. I will write again if I can reproduce it.

**Comment by kai-li-wop** [comment] 2024-11-17 08:12
Ok, I will close this for now because it is not reproducible.

**Closed as not planned by kai-li-wop** 2024-11-17 08:12 UTC
Labels: wontfix
