### ISSUE TITLE
Color black (^8) gets ignored in the player name in the chat 

### ISSUE THREAD

**Issue by VesuviusVenox** [PadWorld-Entertainment/worldofpadman#238] opened 2023-12-03 20:24 UTC
Description of issue: It only seems to affect player names. If your name has the color black in it, it just gets ignored and converts to the adjacent color. 

Steps to reproduce: Change your name to have some black letters in it and then open score board or type something in chat.

**Comment by kai-li-wop** [comment] 2023-12-04 19:53
I had a quick test in ioquake3. There it is ignored in the chat, the name field and the scoreboard but not when typing directly in the console. In WoP it is ignored in the chat, the name field but not in the scoreboard and not when typing directly in the console.

**Comment by kai-li-wop** [comment] 2023-12-05 20:53
@VesuviusVenox: Turn's out it is not a bug, it's a feature. The code comment states:

```// Disallow color black in names to prevent players from getting advantage playing in front of black backgrounds```

I know it is arguable since we have the glow skin feature, so enemies can be highlighted a lot to be more visible, even with dark names, but the name can in fact cover a tiny player being far away. I think we will keep it as is. So no fix for this apart more people from the community wish this to be changed.

**Closed as completed by kai-li-wop** 2023-12-05 20:53 UTC
Labels: good first issue, wontfix
